export const CHAIN_OPTIONS = [
  { name: "Ethereum", symbol: "ETH", id: 1 },
  { name: "Arbitrum", symbol: "ARB", id: 42161 },
  { name: "Optimism", symbol: "OPT", id: 10 },
  { name: "Solana", symbol: "SOL", id: 1151111081099710 },
  { name: "Polygon", symbol: "POL", id: 137 },
  { name: "Base", symbol: "BAS", id: 8453 },
  { name: "Binance Smart Chain", symbol: "BSC", id: 56 },
  { name: "zkSync Era", symbol: "ERA", id: 324 },
  { name: "Linea", symbol: "LNA", id: 59144 },
  { name: "Gnosis (xDAI)", symbol: "DAI", id: 100 },
  { name: "Avalanche", symbol: "AVA", id: 43114 },
  { name: "Fantom", symbol: "FTM", id: 250 },
  { name: "Polygon zkEVM", symbol: "PZE", id: 1101 },
  { name: "Fuse", symbol: "FUS", id: 122 },
  { name: "Boba", symbol: "BOB", id: 288 },
  { name: "Moonbeam", symbol: "MOO", id: 1284 },
  { name: "Moonriver", symbol: "MOR", id: 1285 },
  { name: "Aurora", symbol: "AUR", id: 1313161554 },
  { name: "Metis", symbol: "MAM", id: 1088 },
  { name: "Scroll", symbol: "SCL", id: 534352 },
  { name: "Mode", symbol: "MOD", id: 34443 },
  { name: "Mantle", symbol: "MNT", id: 5000 },
  { name: "Rootstock", symbol: "RSK", id: 30 },
  { name: "Blast", symbol: "BLS", id: 81457 },
  { name: "Celo", symbol: "CEL", id: 42220 },
  { name: "Fraxtal", symbol: "FRA", id: 252 },
];
