import {
  gradientWaves,
  squareGrid,
  floatingShape,
} from "./animatedBackgroundsHtml";

export const THEMES = [
  {
    id: "default",
    name: "Default",
    properties: {
      font: "var(--user-theme-font)",
      fontColor: "var(--user-theme-font-color)",
      headingsFont: "var(--user-theme-headings-font)",
      headingsFontColor: "var(--user-theme-headings-font-color)",
      background: "var(--user-theme-background)",
      backgroundHTML: "",
      musicURL: "https://www.youtube.com/watch?v=dMXlZ4y7OK4&t=1804",
      fidgetBackground: "var(--user-theme-fidget-background)",
      fidgetBorderWidth: "var(--user-theme-fidget-border-width)",
      fidgetBorderColor: "var(--user-theme-fidget-border-color)",
      fidgetShadow: "var(--user-theme-fidget-shadow)",
    },
  },
  {
    id: "redstorm",
    name: "Redstorm",
    properties: {
      font: "Jura",
      fontColor: "#ffffff",
      headingsFont: "Jura",
      headingsFontColor: "#ffffff",
      background: "#E02424",
      backgroundHTML: "",
      musicURL: "https://www.youtube.com/watch?v=dMXlZ4y7OK4&t=1804",
      fidgetBackground: "#C81E1E",
      fidgetBorderWidth: "1px",
      fidgetBorderColor: "#FACA15",
      fidgetShadow: "none",
    },
  },
  {
    id: "purple",
    name: "Purple",
    properties: {
      font: "Inter",
      fontColor: "#FFFFFF",
      headingsFont: "Inter",
      headingsFontColor: "#FFFFFF",
      background: "#4A1D96",
      backgroundHTML: "",
      musicURL: "https://www.youtube.com/watch?v=dMXlZ4y7OK4&t=1804",
      fidgetBackground: "#9061F9",
      fidgetBorderWidth: "1px",
      fidgetBorderColor: "#FDF6B2",
      fidgetShadow: "none",
    },
  },
  {
    id: "yellow",
    name: "Yellow",
    properties: {
      font: "Inter",
      fontColor: "#000000",
      headingsFont: "Inter",
      headingsFontColor: "#000000",
      background: "#FDF6B2",
      backgroundHTML: "",
      musicURL: "https://www.youtube.com/watch?v=dMXlZ4y7OK4&t=1804",
      fidgetBackground: "#FACA15",
      fidgetBorderWidth: "1px",
      fidgetBorderColor: "#B43403",
      fidgetShadow: "none",
    },
  },
  {
    id: "orange",
    name: "Orange",
    properties: {
      font: "Inter",
      fontColor: "#000000",
      headingsFont: "Inter",
      headingsFontColor: "#000000",
      background: "#FACA15",
      backgroundHTML: "",
      musicURL: "https://www.youtube.com/watch?v=dMXlZ4y7OK4&t=1804",
      fidgetBackground: "#4A1D96",
      fidgetBorderWidth: "1px",
      fidgetBorderColor: "#C81E1E",
      fidgetShadow: "none",
    },
  },
  {
    id: "greeny",
    name: "Greeny",
    properties: {
      font: "Inter",
      fontColor: "#FFFFFF",
      headingsFont: "Inter",
      headingsFontColor: "#FFFFFF",
      background: "#4A1D96",
      backgroundHTML: squareGrid,
      musicURL: "https://www.youtube.com/watch?v=dMXlZ4y7OK4&t=1804",
      fidgetBackground: "#31C48D",
      fidgetBorderWidth: "1px",
      fidgetBorderColor: "#FDBA8C",
      fidgetShadow: "none",
    },
  },
  {
    id: "dark",
    name: "Dark",
    properties: {
      font: "Inter",
      fontColor: "#000000",
      headingsFont: "Inter",
      headingsFontColor: "#000000",
      background: "#ffffff",
      backgroundHTML: floatingShape,
      musicURL: "https://www.youtube.com/watch?v=dMXlZ4y7OK4&t=1804",
      fidgetBackground: "#FDFDEA",
      fidgetBorderWidth: "1px",
      fidgetBorderColor: "#111928",
      fidgetShadow: "none",
    },
  },
  {
    id: "scribble",
    name: "Scribble",
    properties: {
      font: "Inter",
      fontColor: "#000000",
      headingsFont: "Inter",
      headingsFontColor: "#000000",
      background: "#fbe9e0",
      backgroundHTML: gradientWaves,
      musicURL: "https://www.youtube.com/watch?v=dMXlZ4y7OK4&t=1804",
      fidgetBackground: "#4A1D96",
      fidgetBorderWidth: "1px",
      fidgetBorderColor: "#C81E1E",
      fidgetShadow: "none",
    },
  },
];
