        },
      },
      fidgetTrayContents: [],
      isEditable: false,
      timestamp,
    },
    Athletes: {
      name: "Athletes",
      displayName: "Athletes",
      layoutID: "gnars-athletes-layout",
      layoutDetails: {
        layoutConfig: {
          layout: [
            {
              w: 6,
              h: 9,
              x: 0,
              y: 0,
              i: "Directory:gnars-holders",
              minW: 4,
              minH: 6,
              moved: false,
              static: false,
              resizeHandles: ["s", "w", "e", "n", "sw", "nw", "se", "ne"],
              isBounded: false,
            },
            {
              w: 6,
              h: 9,
              x: 6,
              y: 0,
              i: "links:gnars-grants",
              minW: 4,
              minH: 4,
              moved: false,
              static: false,
              resizeHandles: ["s", "w", "e", "n", "sw", "nw", "se", "ne"],
              isBounded: false,
            },
            {
              w: 12,
              h: 8,
              x: 0,
              y: 9,
              i: "Video:gnars-reel",
              minW: 6,
              minH: 4,
              moved: false,
              static: false,
              resizeHandles: ["s", "w", "e", "n", "sw", "nw", "se", "ne"],
              isBounded: false,
            },
          ],
        },
        layoutFidget: "grid",
      },
      theme: {
        ...sharedTheme,
        id: "gnars-athletes-theme",
        properties: {
          ...sharedTheme.properties,
          background: "linear-gradient(115deg, #060606 0%, #292929 40%, #ff8a3d 100%)",
          fontColor: "#fffcee",
          headingsFontColor: "#ffe564",
          fidgetBackground: "rgba(0,0,0,0.6)",
          fidgetBorderColor: "#ffe564",
          fidgetShadow: "0 18px 48px rgba(0,0,0,0.45)",
        },
      },
      fidgetInstanceDatums: {
        "Directory:gnars-holders": {
          config: {
            editable: false,
            settings: {
              source: "tokenHolders",
              contractAddress: "0x880Fb3Cf5c6Cc2d7DFC13a993E839a9411200C17",
              network: "base",
              layoutStyle: "cards",
              include: "holdersWithFarcasterAccount",
              assetType: "nft",
              sortBy: "tokenHoldings",
            },
            data: {},
          },
          fidgetType: "Directory",
          id: "Directory:gnars-holders",
        },
        "links:gnars-grants": {
          config: {
            editable: false,
            settings: {
              title: "Active Programs",
              links: [
                { title: "Daily Auction", url: "https://gnars.wtf", description: "Bid on today's Gnar" },
                { title: "Grants app", url: "https://airtable.com/apppxNTUjEC2zYoyv/shrP0uCSmS7AYA9Y9", description: "Submit sponsorship" },
                { title: "Nouns Center", url: "https://nouns.center/dao/gnars", description: "Stats & treasury" },
              ],
            },
            data: {},
          },
          fidgetType: "links",
          id: "links:gnars-grants",
        },
        "Video:gnars-reel": {
          config: {
            editable: false,
            settings: {
              url: "https://www.youtube.com/watch?v=1SIwxLBzME4",
              autoplay: false,
              background: "var(--user-theme-fidget-background)",
            },
            data: {},
          },
          fidgetType: "Video",
          id: "Video:gnars-reel",
        },
      },
      fidgetTrayContents: [],
      isEditable: false,
      timestamp,
    },
    Resources: {
      name: "Resources",
      displayName: "Resources",
      layoutID: "gnars-resources-layout",
      layoutDetails: {
        layoutConfig: {
          layout: [
            {
              w: 5,
              h: 8,
              x: 0,
              y: 0,
              i: "links:gnars-links",
              minW: 3,
              minH: 4,
              moved: false,
              static: false,
              resizeHandles: ["s", "w", "e", "n", "sw", "nw", "se", "ne"],
              isBounded: false,
            },
            {
              w: 7,
              h: 8,
              x: 5,
              y: 0,
              i: "Rss:gnars-updates",
              minW: 3,
              minH: 4,
              moved: false,
              static: false,
              resizeHandles: ["s", "w", "e", "n", "sw", "nw", "se", "ne"],
              isBounded: false,
            },
            {
              w: 12,
              h: 8,
              x: 0,
              y: 8,
              i: "SnapShot:gnars-proposals",
              minW: 4,
              minH: 4,
              moved: false,
              static: false,
              resizeHandles: ["s", "w", "e", "n", "sw", "nw", "se", "ne"],
              isBounded: false,
            },
          ],
        },
        layoutFidget: "grid",
      },
      theme: {
        ...sharedTheme,
        id: "gnars-resources-theme",
        properties: {
          ...sharedTheme.properties,
          background: "#fffef8",
        },
      },
      fidgetInstanceDatums: {
        "links:gnars-links": {
          config: {
            editable: false,
            settings: {
              title: "Essential links",
              links: [
                { title: "Docs", url: "https://docs.gnars.wtf" },
                { title: "Farcaster /gnars", url: "https://warpcast.com/~/channel/gnars" },
                { title: "BaseScan Token", url: "https://basescan.org/token/0x0cf0c3b75d522290d7d12c74d7f1f0cc47ccb23b" },
                { title: "Discord", url: "https://discord.gg/gnars" },
              ],
            },
            data: {},
          },
          fidgetType: "links",
          id: "links:gnars-links",
        },
        "Rss:gnars-updates": {
          config: {
            editable: false,
            settings: {
              feedUrl: "https://mirror.xyz/0x18022190fb070012002E6A06e5233b208C0Fb3d5/feed",
              title: "Mirror updates",
            },
            data: {},
          },
          fidgetType: "Rss",
          id: "Rss:gnars-updates",
        },
        "SnapShot:gnars-proposals": {
          config: {
            editable: false,
            settings: {
              space: "gnarsdao.eth",
              title: "Snapshot Proposals",
              background: "var(--user-theme-fidget-background)",
            },
            data: {},
          },
          fidgetType: "SnapShot",
          id: "SnapShot:gnars-proposals",
        },
      },
      fidgetTrayContents: [],
      isEditable: false,
      timestamp,
    },
  },
  layout: {
    defaultLayoutFidget: "grid",
    gridSpacing: 16,
    theme: {
      background: "#fff07a",
      fidgetBackground: "#fff9d8",
      font: "'Inter', sans-serif",
      fontColor: "#111111",
    },
  },
};
