const timestamp = new Date().toISOString();

const homeTabTheme = {
  id: "gnars-home-tab",
  name: "Gnars Home",
  properties: {
    background: "#ffe564",
    backgroundHTML: "",
    fidgetBackground: "#ffffff",
    fidgetBorderColor: "transparent",
    fidgetBorderWidth: "0px",
    fidgetShadow: "none",
    fidgetBorderRadius: "0px",
    font: "'Inter', sans-serif",
    fontColor: "#111111",
    gridSpacing: "0",
    headingsFont: "'Space Grotesk', 'Inter', sans-serif",
    headingsFontColor: "#111111",
    musicURL: "",
  },
};

const socialTabTheme = {
  id: "gnars-social-tab",
  name: "Gnars Social",
  properties: {
    background: "linear-gradient(135deg, #111111 0%, #ff8a3d 100%)",
    backgroundHTML: "",
    fidgetBackground: "rgba(255,255,255,0.92)",
    fidgetBorderColor: "rgba(255,229,100,0.8)",
    fidgetBorderWidth: "3px",
    fidgetShadow: "0 8px 32px rgba(0,0,0,0.35)",
    fidgetBorderRadius: "18px",
    font: "'Space Grotesk', 'Inter', sans-serif",
    fontColor: "#111111",
    gridSpacing: "20",
    headingsFont: "'Space Grotesk', 'Inter', sans-serif",
    headingsFontColor: "#111111",
    musicURL: "",
  },
};

const docsTabTheme = {
  id: "gnars-docs-tab",
  name: "Gnars Docs",
  properties: {
    background: "#ffffff",
    backgroundHTML: "",
    fidgetBackground: "#ffffff",
    fidgetBorderColor: "#f1f1f1",
    fidgetBorderWidth: "1px",
    fidgetShadow: "none",
    fidgetBorderRadius: "0px",
    font: "'Inter', sans-serif",
    fontColor: "#111111",
    gridSpacing: "0",
    headingsFont: "'Space Grotesk', 'Inter', sans-serif",
    headingsFontColor: "#111111",
    musicURL: "",
  },
};

export const gnarsHomePage = {
  defaultTab: "Home",
  tabOrder: ["Home", "Social", "Docs"],
  tabs: {
    Home: {
      name: "Home",
      displayName: "Home",
      layoutID: "gnars-home-embed",
      layoutDetails: {
        layoutConfig: {
          layout: [
            {
              w: 12,
              h: 24,
              x: 0,
              y: 0,
              i: "iframe:gnars-home",
              minW: 12,
              maxW: 36,
              minH: 12,
              maxH: 36,
              moved: false,
              static: false,
              resizeHandles: ["s", "w", "e", "n", "sw", "nw", "se", "ne"],
              isBounded: false,
            },
          ],
        },
        layoutFidget: "grid",
      },
      theme: homeTabTheme,
      fidgetInstanceDatums: {
        "iframe:gnars-home": {
          config: {
            data: {},
            editable: false,
            settings: {
              url: "https://gnars-shadcn.vercel.app/",
              showOnMobile: true,
              isScrollable: true,
              background: "var(--user-theme-fidget-background)",
              fidgetBorderColor: "var(--user-theme-fidget-border-color)",
              fidgetBorderWidth: "var(--user-theme-fidget-border-width)",
              fidgetShadow: "var(--user-theme-fidget-shadow)",
            },
          },
          fidgetType: "iframe",
          id: "iframe:gnars-home",
        },
      },
      fidgetTrayContents: [],
      isEditable: false,
      timestamp,
    },
    Social: {
      name: "Social",
      displayName: "Social",
      layoutID: "gnars-social",
      layoutDetails: {
        layoutConfig: {
          layout: [
            {
              w: 6,
              h: 10,
              x: 0,
              y: 0,
              i: "feed:gnars-channel",
              minW: 4,
              maxW: 36,
              minH: 2,
              maxH: 36,
              moved: false,
              static: false,
              resizeHandles: ["s", "w", "e", "n", "sw", "nw", "se", "ne"],
              isBounded: false,
            },
            {
              w: 6,
              h: 6,
              x: 6,
              y: 0,
              i: "feed:gnars-gnar",
              minW: 4,
              maxW: 36,
              minH: 2,
              maxH: 36,
              moved: false,
              static: false,
              resizeHandles: ["s", "w", "e", "n", "sw", "nw", "se", "ne"],
              isBounded: false,
            },
            {
              w: 4,
              h: 4,
              x: 6,
              y: 6,
              i: "feed:gnars-token",
              minW: 4,
              maxW: 36,
              minH: 2,
              maxH: 36,
              moved: false,
              static: false,
              resizeHandles: ["s", "w", "e", "n", "sw", "nw", "se", "ne"],
              isBounded: false,
            },
            {
              w: 2,
              h: 4,
              x: 10,
              y: 6,
              i: "links:gnars-social",
              minW: 2,
              maxW: 36,
              minH: 2,
              maxH: 36,
              moved: false,
              static: false,
              resizeHandles: ["s", "w", "e", "n", "sw", "nw", "se", "ne"],
              isBounded: false,
            },
          ],
        },
        layoutFidget: "grid",
      },
      theme: socialTabTheme,
      fidgetInstanceDatums: {
        "feed:gnars-channel": {
          config: {
            data: {},
            editable: true,
            settings: {
              background: "var(--user-theme-fidget-background)",
              feedType: "filter",
              filterType: "channel_id",
              channel: "gnars",
              selectPlatform: { icon: "/images/farcaster.jpeg", name: "Farcaster" },
              fidgetBorderColor: "var(--user-theme-fidget-border-color)",
              fidgetBorderWidth: "var(--user-theme-fidget-border-width)",
              fidgetShadow: "var(--user-theme-fidget-shadow)",
              fontFamily: "var(--user-theme-font)",
              fontColor: "var(--user-theme-font-color)",
              showOnMobile: true,
              style: "light",
              Xhandle: "gnars_dao",
              keyword: "",
              username: "",
              users: "",
            },
          },
          fidgetType: "feed",
          id: "feed:gnars-channel",
        },
        "feed:gnars-gnar": {
          config: {
            data: {},
            editable: true,
            settings: {
              background: "var(--user-theme-fidget-background)",
              feedType: "filter",
              filterType: "keyword",
              keyword: "gnar",
              selectPlatform: { icon: "/images/farcaster.jpeg", name: "Farcaster" },
              fidgetBorderColor: "var(--user-theme-fidget-border-color)",
              fidgetBorderWidth: "var(--user-theme-fidget-border-width)",
              fidgetShadow: "var(--user-theme-fidget-shadow)",
              fontFamily: "var(--user-theme-font)",
              fontColor: "var(--user-theme-font-color)",
              showOnMobile: true,
              style: "light",
              Xhandle: "gnars_dao",
              channel: "",
              username: "",
              users: "",
            },
          },
          fidgetType: "feed",
          id: "feed:gnars-gnar",
        },
        "feed:gnars-token": {
          config: {
            data: {},
            editable: true,
            settings: {
              background: "var(--user-theme-fidget-background)",
              feedType: "filter",
              filterType: "keyword",
              keyword: "$GNARS",
              selectPlatform: { icon: "/images/farcaster.jpeg", name: "Farcaster" },
              fidgetBorderColor: "var(--user-theme-fidget-border-color)",
              fidgetBorderWidth: "var(--user-theme-fidget-border-width)",
              fidgetShadow: "var(--user-theme-fidget-shadow)",
              fontFamily: "var(--user-theme-font)",
              fontColor: "var(--user-theme-font-color)",
              showOnMobile: true,
              style: "light",
              Xhandle: "gnars_dao",
              channel: "",
              username: "",
              users: "",
            },
          },
          fidgetType: "feed",
          id: "feed:gnars-token",
        },
        "links:gnars-social": {
          config: {
            data: {},
            editable: true,
            settings: {
              DescriptionColor: "var(--user-theme-font-color)",
              HeaderColor: "var(--user-theme-headings-font-color)",
              background: "var(--user-theme-fidget-background)",
              css: "",
              fidgetBorderColor: "var(--user-theme-fidget-border-color)",
              fidgetBorderWidth: "var(--user-theme-fidget-border-width)",
              fidgetShadow: "var(--user-theme-fidget-shadow)",
              fontFamily: "Theme Font",
              headingsFontFamily: "var(--user-theme-headings-font)",
              itemBackground: "var(--user-theme-fidget-background)",
              links: [
                { text: "Twitter / X", url: "https://twitter.com/gnars_dao", description: "@gnars_dao" },
                { text: "GitHub", url: "https://github.com/gnars-dao", description: "github.com/gnars-dao" },
                { text: "Farcaster", url: "https://farcaster.xyz/~/channel/gnars", description: "/gnars channel" },
                { text: "Instagram", url: "https://www.instagram.com/gnarsdao/", description: "@gnarsdao" },
                { text: "Zora", url: "https://zora.co/@gnars", description: "Mint & drops" },
              ],
              showOnMobile: true,
              title: "Stay Connected",
              viewMode: "list",
            },
          },
          fidgetType: "links",
          id: "links:gnars-social",
        },
      },
      fidgetTrayContents: [],
      isEditable: false,
      timestamp,
    },
    Docs: {
      name: "Docs",
      displayName: "Docs",
      layoutID: "gnars-docs",
      layoutDetails: {
        layoutConfig: {
          layout: [
            {
              w: 12,
              h: 24,
              x: 0,
              y: 0,
              i: "iframe:gnars-docs",
              minW: 12,
              maxW: 36,
              minH: 12,
              maxH: 36,
              moved: false,
              static: false,
              resizeHandles: ["s", "w", "e", "n", "sw", "nw", "se", "ne"],
              isBounded: false,
            },
          ],
        },
        layoutFidget: "grid",
      },
      theme: docsTabTheme,
      fidgetInstanceDatums: {
        "iframe:gnars-docs": {
          config: {
            data: {},
            editable: true,
            settings: {
              url: "https://gnars-docs.vercel.app/",
              showOnMobile: true,
              isScrollable: true,
              background: "var(--user-theme-fidget-background)",
              fidgetBorderColor: "var(--user-theme-fidget-border-color)",
              fidgetBorderWidth: "var(--user-theme-fidget-border-width)",
              fidgetShadow: "var(--user-theme-fidget-shadow)",
            },
          },
          fidgetType: "iframe",
          id: "iframe:gnars-docs",
        },
      },
      fidgetTrayContents: [],
      isEditable: false,
      timestamp,
    },
  },
  layout: {
    defaultLayoutFidget: "grid",
    gridSpacing: 16,
    theme: {
      background: "#fff07a",
      fidgetBackground: "#fff9d8",
      font: "'Inter', sans-serif",
      fontColor: "#111111",
    },
  },
};
