export const nounsAssets = {
  logos: {
    main: "/images/nounspace_logo.png",
    icon: "/images/mini_app_icon.png",
    favicon: "/images/favicon.ico",
    appleTouch: "/images/apple-touch-icon.png",
    og: "/images/nounspace_og_low.png",
    splash: "/images/icon-192x192.png",
  },
  images: {
    hero: "/images/icon-192x192.png",
    background: "/images/space-background.png",
    tutorial: "/images/tutorial.webm",
    loading: "/public/noun-loading-skull.gif",
    notFound: "/images/UserNotFound.png",
    chainEmoji: "/images/chainEmoji.png",
    farcaster: "/images/farcaster.jpeg",
    farcasterNude: "/images/farcaster_nude.png",
    noggles: "/images/noggles.svg",
    nounsYellow: "/images/nouns_yellow_logo.jpg",
    badge: "/images/badge.png",
    activeBadge: "/images/ActiveBadge.webp",
    tomAlerts: "/images/tom_alerts.png",
    clankerGalaxy: "/images/clanker_galaxy.png",
    rainforest: "/images/rainforest.png",
  },
  learn: {
    governance: "/learn/governance.png",
    noggles: "/learn/noggles.png",
    whatAreNouns: "/learn/what-are-nouns.png",
  },
  nounsSamples: [
    "/nouns-samples/1.svg",
    "/nouns-samples/10.svg",
    "/nouns-samples/1111.svg",
    "/nouns-samples/125.svg",
    "/nouns-samples/1337.svg",
    "/nouns-samples/150.svg",
    "/nouns-samples/208.svg",
    "/nouns-samples/25.svg",
    "/nouns-samples/256.svg",
    "/nouns-samples/314.svg",
    "/nouns-samples/365.svg",
    "/nouns-samples/42.svg",
    "/nouns-samples/420.svg",
    "/nouns-samples/512.svg",
    "/nouns-samples/777.svg",
    "/nouns-samples/808.svg",
    "/nouns-samples/903.svg",
    "/nouns-samples/99.svg",
  ],
  exploreIcons: [
    "/images/explore-icons/icon1.png",
    "/images/explore-icons/icon2.png",
    "/images/explore-icons/icon3.png",
    "/images/explore-icons/icon4.png",
    "/images/explore-icons/icon5.png",
    "/images/explore-icons/icon6.png",
    "/images/explore-icons/icon7.png",
    "/images/explore-icons/icon8.png",
    "/images/explore-icons/icon9.png",
  ],
};
