create table "public"."fidRegistrations" (
    "id" bigint generated by default as identity not null,
    "created" timestamp with time zone not null default now(),
    "fid" bigint not null,
    "identityPublicKey" character varying not null,
    "signature" character varying not null,
    "signingPublicKey" character varying not null,
    "signingKeyLastValidatedAt" timestamp without time zone not null,
    "isSigningKeyValid" boolean not null
);


alter table "public"."fidRegistrations" enable row level security;

create table "public"."spaceRegistrations" (
    "spaceId" uuid not null default gen_random_uuid(),
    "fid" bigint not null,
    "spaceName" character varying not null,
    "signature" character varying not null,
    "identityPublicKey" character varying not null
);


alter table "public"."spaceRegistrations" enable row level security;

CREATE UNIQUE INDEX fidregistrations_pkey ON public."fidRegistrations" USING btree (id);

CREATE UNIQUE INDEX spaceregistrations_pkey ON public."spaceRegistrations" USING btree ("spaceId");

alter table "public"."fidRegistrations" add constraint "fidregistrations_pkey" PRIMARY KEY using index "fidregistrations_pkey";

alter table "public"."spaceRegistrations" add constraint "spaceregistrations_pkey" PRIMARY KEY using index "spaceregistrations_pkey";

grant delete on table "public"."fidRegistrations" to "anon";

grant insert on table "public"."fidRegistrations" to "anon";

grant references on table "public"."fidRegistrations" to "anon";

grant select on table "public"."fidRegistrations" to "anon";

grant trigger on table "public"."fidRegistrations" to "anon";

grant truncate on table "public"."fidRegistrations" to "anon";

grant update on table "public"."fidRegistrations" to "anon";

grant delete on table "public"."fidRegistrations" to "authenticated";

grant insert on table "public"."fidRegistrations" to "authenticated";

grant references on table "public"."fidRegistrations" to "authenticated";

grant select on table "public"."fidRegistrations" to "authenticated";

grant trigger on table "public"."fidRegistrations" to "authenticated";

grant truncate on table "public"."fidRegistrations" to "authenticated";

grant update on table "public"."fidRegistrations" to "authenticated";

grant delete on table "public"."fidRegistrations" to "service_role";

grant insert on table "public"."fidRegistrations" to "service_role";

grant references on table "public"."fidRegistrations" to "service_role";

grant select on table "public"."fidRegistrations" to "service_role";

grant trigger on table "public"."fidRegistrations" to "service_role";

grant truncate on table "public"."fidRegistrations" to "service_role";

grant update on table "public"."fidRegistrations" to "service_role";

grant delete on table "public"."spaceRegistrations" to "anon";

grant insert on table "public"."spaceRegistrations" to "anon";

grant references on table "public"."spaceRegistrations" to "anon";

grant select on table "public"."spaceRegistrations" to "anon";

grant trigger on table "public"."spaceRegistrations" to "anon";

grant truncate on table "public"."spaceRegistrations" to "anon";

grant update on table "public"."spaceRegistrations" to "anon";

grant delete on table "public"."spaceRegistrations" to "authenticated";

grant insert on table "public"."spaceRegistrations" to "authenticated";

grant references on table "public"."spaceRegistrations" to "authenticated";

grant select on table "public"."spaceRegistrations" to "authenticated";

grant trigger on table "public"."spaceRegistrations" to "authenticated";

grant truncate on table "public"."spaceRegistrations" to "authenticated";

grant update on table "public"."spaceRegistrations" to "authenticated";

grant delete on table "public"."spaceRegistrations" to "service_role";

grant insert on table "public"."spaceRegistrations" to "service_role";

grant references on table "public"."spaceRegistrations" to "service_role";

grant select on table "public"."spaceRegistrations" to "service_role";

grant trigger on table "public"."spaceRegistrations" to "service_role";

grant truncate on table "public"."spaceRegistrations" to "service_role";

grant update on table "public"."spaceRegistrations" to "service_role";


