create table "public"."sharedContentAccessRequests" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "cid" character varying not null,
    "publicKey" character varying not null,
    "signature" character varying not null
);


alter table "public"."sharedContentAccessRequests" enable row level security;

create table "public"."sharedContentRegistrations" (
    "cid" character varying not null,
    "timestamp" timestamp with time zone not null,
    "publicKey" character varying not null,
    "name" character varying,
    "signature" character varying not null
);


alter table "public"."sharedContentRegistrations" enable row level security;

alter table "public"."spaceRegistrations" add column "contractAddress" text;

alter table "public"."spaceRegistrations" alter column "fid" drop not null;

CREATE UNIQUE INDEX "sharedContentAccessRequests_pkey" ON public."sharedContentAccessRequests" USING btree (id);

CREATE UNIQUE INDEX "sharedContentRegistrations_pkey" ON public."sharedContentRegistrations" USING btree (cid);

alter table "public"."sharedContentAccessRequests" add constraint "sharedContentAccessRequests_pkey" PRIMARY KEY using index "sharedContentAccessRequests_pkey";

alter table "public"."sharedContentRegistrations" add constraint "sharedContentRegistrations_pkey" PRIMARY KEY using index "sharedContentRegistrations_pkey";

alter table "public"."sharedContentAccessRequests" add constraint "public_sharedContentAccessRequests_cid_fkey" FOREIGN KEY (cid) REFERENCES "sharedContentRegistrations"(cid) not valid;

alter table "public"."sharedContentAccessRequests" validate constraint "public_sharedContentAccessRequests_cid_fkey";

grant delete on table "public"."sharedContentAccessRequests" to "anon";

grant insert on table "public"."sharedContentAccessRequests" to "anon";

grant references on table "public"."sharedContentAccessRequests" to "anon";

grant select on table "public"."sharedContentAccessRequests" to "anon";

grant trigger on table "public"."sharedContentAccessRequests" to "anon";

grant truncate on table "public"."sharedContentAccessRequests" to "anon";

grant update on table "public"."sharedContentAccessRequests" to "anon";

grant delete on table "public"."sharedContentAccessRequests" to "authenticated";

grant insert on table "public"."sharedContentAccessRequests" to "authenticated";

grant references on table "public"."sharedContentAccessRequests" to "authenticated";

grant select on table "public"."sharedContentAccessRequests" to "authenticated";

grant trigger on table "public"."sharedContentAccessRequests" to "authenticated";

grant truncate on table "public"."sharedContentAccessRequests" to "authenticated";

grant update on table "public"."sharedContentAccessRequests" to "authenticated";

grant delete on table "public"."sharedContentAccessRequests" to "service_role";

grant insert on table "public"."sharedContentAccessRequests" to "service_role";

grant references on table "public"."sharedContentAccessRequests" to "service_role";

grant select on table "public"."sharedContentAccessRequests" to "service_role";

grant trigger on table "public"."sharedContentAccessRequests" to "service_role";

grant truncate on table "public"."sharedContentAccessRequests" to "service_role";

grant update on table "public"."sharedContentAccessRequests" to "service_role";

grant delete on table "public"."sharedContentRegistrations" to "anon";

grant insert on table "public"."sharedContentRegistrations" to "anon";

grant references on table "public"."sharedContentRegistrations" to "anon";

grant select on table "public"."sharedContentRegistrations" to "anon";

grant trigger on table "public"."sharedContentRegistrations" to "anon";

grant truncate on table "public"."sharedContentRegistrations" to "anon";

grant update on table "public"."sharedContentRegistrations" to "anon";

grant delete on table "public"."sharedContentRegistrations" to "authenticated";

grant insert on table "public"."sharedContentRegistrations" to "authenticated";

grant references on table "public"."sharedContentRegistrations" to "authenticated";

grant select on table "public"."sharedContentRegistrations" to "authenticated";

grant trigger on table "public"."sharedContentRegistrations" to "authenticated";

grant truncate on table "public"."sharedContentRegistrations" to "authenticated";

grant update on table "public"."sharedContentRegistrations" to "authenticated";

grant delete on table "public"."sharedContentRegistrations" to "service_role";

grant insert on table "public"."sharedContentRegistrations" to "service_role";

grant references on table "public"."sharedContentRegistrations" to "service_role";

grant select on table "public"."sharedContentRegistrations" to "service_role";

grant trigger on table "public"."sharedContentRegistrations" to "service_role";

grant truncate on table "public"."sharedContentRegistrations" to "service_role";

grant update on table "public"."sharedContentRegistrations" to "service_role";


