create table "public"."spaceOrderings" (
    "id" bigint generated by default as identity not null,
    "timestamp" timestamp with time zone not null,
    "fid" bigint not null,
    "identityPublicKey" character varying not null,
    "signature" character varying not null,
    "ordering" uuid[] not null
);


alter table "public"."spaceOrderings" enable row level security;

alter table "public"."spaceRegistrations" drop column "isDefault";

CREATE INDEX "fidRegistrations_fid_idx" ON public."fidRegistrations" USING btree (fid);

CREATE UNIQUE INDEX "spaceOrderings_pkey" ON public."spaceOrderings" USING btree (id);

CREATE INDEX "spaceRegistrations_fid_idx" ON public."spaceRegistrations" USING btree (fid);

alter table "public"."spaceOrderings" add constraint "spaceOrderings_pkey" PRIMARY KEY using index "spaceOrderings_pkey";

alter table "public"."spaceOrderings" add constraint "public_spaceOrderings_fid_fkey" FOREIGN KEY (fid) REFERENCES "fidRegistrations"(fid) not valid;

alter table "public"."spaceOrderings" validate constraint "public_spaceOrderings_fid_fkey";

grant delete on table "public"."spaceOrderings" to "anon";

grant insert on table "public"."spaceOrderings" to "anon";

grant references on table "public"."spaceOrderings" to "anon";

grant select on table "public"."spaceOrderings" to "anon";

grant trigger on table "public"."spaceOrderings" to "anon";

grant truncate on table "public"."spaceOrderings" to "anon";

grant update on table "public"."spaceOrderings" to "anon";

grant delete on table "public"."spaceOrderings" to "authenticated";

grant insert on table "public"."spaceOrderings" to "authenticated";

grant references on table "public"."spaceOrderings" to "authenticated";

grant select on table "public"."spaceOrderings" to "authenticated";

grant trigger on table "public"."spaceOrderings" to "authenticated";

grant truncate on table "public"."spaceOrderings" to "authenticated";

grant update on table "public"."spaceOrderings" to "authenticated";

grant delete on table "public"."spaceOrderings" to "service_role";

grant insert on table "public"."spaceOrderings" to "service_role";

grant references on table "public"."spaceOrderings" to "service_role";

grant select on table "public"."spaceOrderings" to "service_role";

grant trigger on table "public"."spaceOrderings" to "service_role";

grant truncate on table "public"."spaceOrderings" to "service_role";

grant update on table "public"."spaceOrderings" to "service_role";


