CREATE TABLE IF NOT EXISTS "public"."lastSeenNotificationCursors" (
    "id" bigint generated by default as identity NOT NULL,
    "created" timestamp with time zone NOT NULL default now(),
    "fid" bigint NOT NULL,
    "identityPublicKey" character varying NOT NULL,
    "lastSeenTimestamp" timestamp with time zone NOT NULL
);

ALTER TABLE "public"."lastSeenNotificationCursors" ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX IF NOT EXISTS "lastSeenNotificationCursors_identityPublicKey_fid"
ON public."lastSeenNotificationCursors" USING btree (fid, "identityPublicKey");

CREATE UNIQUE INDEX notificationcursors_pkey
ON public."lastSeenNotificationCursors" USING btree (id);

ALTER TABLE "public"."lastSeenNotificationCursors"
ADD CONSTRAINT "notificationcursors_pkey" PRIMARY KEY
USING INDEX "notificationcursors_pkey";

GRANT ALL ON TABLE "public"."lastSeenNotificationCursors" TO "authenticated";
GRANT ALL ON TABLE "public"."lastSeenNotificationCursors" TO "service_role";